# Generated by Django 5.2.1 on 2025-05-18 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Okay', 'Okay')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='book_images/')),
                ('location', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, to='users.genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('preferred_genres', models.ManyToManyField(blank=True, related_name='preferred_books', to='users.genre')),
            ],
        ),
    ]
