# Generated by Django 5.2.1 on 2025-05-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_book_likes_book_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploaded_at',
        ),
    ]
