# Generated by Django 5.2.1 on 2025-05-20 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_book_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
